[package]
name = "ping-pong"
version = "0.1.0"
authors = ["Tobin C. Harding <tobin@coblox.tech>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
clap = "2.32"
futures = "0.3"
libp2p = "0.19"
tokio = { version = "0.2", features = ["rt-threaded", "time", "macros", "sync"] }
